import {
  BadRequestException,
  Body,
  Controller,
  Get,
  HttpCode,
  HttpStatus,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiOperation,
  ApiPropertyOptional,
  ApiQuery,
  ApiTags,
} from '@nestjs/swagger';
import {
  IsArray,
  IsEnum,
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  Min,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { OrderStatus } from '@prisma/client';
import { OrdersService } from './orders.service';
import { Roles } from '../common/decorators/roles.decorator';
import { CurrentUser } from '../common/decorators/current-user.decorator';
import { RequirePermissions } from '../common/decorators/permissions.decorator';
import { Permissions } from '../common/permissions';
import { UserRole, type JwtPayload } from '@pharmasyn/types';

export class CheckoutItemDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID()
  supplierProductId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID()
  marketplaceOfferId?: string;

  @IsInt()
  @Min(1)
  quantity: number;

  // Accepted for backwards compatibility only. The server always recalculates prices.
  @ApiPropertyOptional({ deprecated: true })
  @IsOptional()
  @IsNumber()
  @Min(0)
  price?: number;
}

export class CheckoutGroupDto {
  @IsUUID()
  supplierId: string;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CheckoutItemDto)
  items: CheckoutItemDto[];

  @IsOptional()
  @IsString()
  @MaxLength(1000)
  notes?: string;
}

export class CreateOrderDto {
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CheckoutGroupDto)
  groups: CheckoutGroupDto[];

  @ApiPropertyOptional({
    description: 'Stable UUID generated by the client for idempotent retries',
  })
  @IsOptional()
  @IsUUID()
  clientMutationId?: string;

  @ApiPropertyOptional({
    description: 'Stable device identifier for future offline sync',
  })
  @IsOptional()
  @IsString()
  @MaxLength(128)
  deviceId?: string;
}

export class UpdateOrderStatusDto {
  @IsEnum(OrderStatus)
  status: OrderStatus;
}

@ApiTags('orders')
@ApiBearerAuth()
@Controller({ path: 'orders', version: '1' })
export class OrdersController {
  constructor(private readonly ordersService: OrdersService) {}

  @Post('checkout')
  @Roles(UserRole.PHARMACY)
  @RequirePermissions(Permissions.ORDERS_CREATE)
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Create an idempotent multi-seller checkout' })
  checkout(@CurrentUser() user: JwtPayload, @Body() dto: CreateOrderDto) {
    if (!user.orgId)
      throw new BadRequestException('No organization associated');
    return this.ordersService.checkout(user.orgId, user.sub, dto);
  }

  @Get('pharmacy')
  @Roles(UserRole.PHARMACY)
  @RequirePermissions(Permissions.ORDERS_READ)
  @ApiOperation({ summary: 'Get pharmacy purchase orders' })
  @ApiQuery({ name: 'page', required: false })
  @ApiQuery({ name: 'limit', required: false })
  findPharmacyOrders(
    @CurrentUser() user: JwtPayload,
    @Query('page') page?: string,
    @Query('limit') limit?: string,
  ) {
    if (!user.orgId)
      throw new BadRequestException('No organization associated');
    return this.ordersService.findPharmacyOrders(
      user.orgId,
      Number(page) || 1,
      Number(limit) || 20,
    );
  }

  @Get('supplier')
  @Roles(UserRole.SUPPLIER)
  @RequirePermissions(Permissions.ORDERS_READ)
  @ApiOperation({ summary: 'Get supplier sales orders' })
  findSupplierOrders(
    @CurrentUser() user: JwtPayload,
    @Query('page') page?: string,
    @Query('limit') limit?: string,
    @Query('status') status?: OrderStatus,
  ) {
    if (!user.orgId)
      throw new BadRequestException('No organization associated');
    return this.ordersService.findSupplierOrders(
      user.orgId,
      Number(page) || 1,
      Number(limit) || 20,
      status,
    );
  }

  @Get(':id')
  @Roles(UserRole.PHARMACY, UserRole.SUPPLIER)
  @RequirePermissions(Permissions.ORDERS_READ)
  @ApiOperation({ summary: 'Get an order visible to the current organization' })
  getOrderDetails(@CurrentUser() user: JwtPayload, @Param('id') id: string) {
    if (!user.orgId)
      throw new BadRequestException('No organization associated');
    return this.ordersService.getOrderDetails(id, user.orgId, user.role);
  }

  @Patch(':id/status')
  @Roles(UserRole.SUPPLIER, UserRole.PHARMACY)
  @RequirePermissions(Permissions.ORDERS_MANAGE)
  @ApiOperation({
    summary:
      'Apply a validated order transition; sellers fulfill through SHIPPED and the buyer confirms DELIVERED',
  })
  updateStatus(
    @CurrentUser() user: JwtPayload,
    @Param('id') id: string,
    @Body() dto: UpdateOrderStatusDto,
  ) {
    if (!user.orgId)
      throw new BadRequestException('No organization associated');
    return this.ordersService.updateOrderStatus(
      id,
      user.orgId,
      user.role,
      dto.status,
      user.sub,
    );
  }
}
